#######################
# format
#######################
# Move kube later
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$kubernetes\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

#######################
# customize stuff
#######################
[aws]
disabled = true
format = 'on [$symbol$region]($style) '
style = 'bold blue'
symbol = '🅰 '

# https://starship.rs/config/#kubernetes
[kubernetes]
disabled = true
format = 'on [⛵$context \($namespace\)](green) '

# this simplifies the cluster line to:
# > sandbox-delivery-use1-002
[kubernetes.context_aliases]
'.*cluster/aws-otk-(?P<var_cluster>[\w-]+)' = '$var_cluster'

#######################
# disable stuff
#######################
[docker_context]
disabled = true

[python]
disabled = true

[helm]
disabled = true

[package]
disabled = true

[git_branch]
disabled = false

[git_status]
disabled = false

[pulumi]
disabled = true
